### ISSUE TITLE
Parsing of array literals broken

### ISSUE THREAD

**Issue by drslump** [nishants/wirestub#1]
I'm getting a templating error when using a template like the following:

```js
{
  "foo": {
    "id": "{{request.body.id}}",
    "bar": [
      {
        "baz": 100
      }
    ]
  }
}
```

```
TypeError: [{baz=100}] has no such function "isDirective"

<eval>:305 TypeError: [{baz=100}] has no such function "isDirective"
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.linkBean(NashornBottomLinker.java:106)
	at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.getGuardedInvocation(NashornBottomLinker.java:71)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
	at jdk.nashorn.internal.scripts.Script$Recompilation$8$11932AAA$\^eval\_.jeyson$compile(<eval>:305)
	at jdk.nashorn.internal.scripts.Script$Recompilation$8$11932AAA$\^eval\_.jeyson$compile(<eval>:313)
	at jdk.nashorn.internal.scripts.Script$Recompilation$8$11932AAA$\^eval\_.jeyson$compile(<eval>:313)
	at jdk.nashorn.internal.scripts.Script$Recompilation$5$11782AAA$\^eval\_.jeyson$$compile(<eval>:288)
	at jdk.nashorn.internal.scripts.Script$Recompilation$4$13095AA$\^eval\_.jeyson$compile-1(<eval>:322)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:644)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:228)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117)
	at social.amoeba.jeyson.Jeyson.compile(Jeyson.java:28)
```

It seems arrays are not properly handled by the nashorn engine and breaks the template logic.

Additionally, the error results on a `200 OK` reponses with the template as body. Is that intended? It feels like these condition should respond with a `500 Internal Server Error` with the actual error in the body, that way these kind of issues would be easier to detect and fix.

**Comment by nishants** [comment]
Fixed.
